name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Secret reference for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Secret reference for Docker password

      - name: Build Docker image
        run: |
          docker build -t siraj715/foryaml2:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push siraj715/foryaml2:latest
