name: super-liner
on: push
jobs:
super-lint:
name: lint code base
runs-on: ubuntu -22.4
steps:
-name: checkout code
user: action/checkout@v2
uses: github/super-liner@v3
env:
DEFAULT_BRANCH: main
GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
