name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the `main` branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Run this on an Ubuntu server

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub (with secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # This refers to your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # This refers to your Docker Hub password (or access token)

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t siraj715/foryaml2:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push siraj715/foryaml2:latest
