name: Trigger another workflow
on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger second workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: second.yml  # Name of the other workflow
          ref: refs/heads/main


