name: super-liner
on: 
  push:
jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: run super-liner
        uses: github/super-liner@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

