name: Simple Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Print Hello World
        run: echo "Hello, World! The workflow is running."

